# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

debug = False

limit = 4000000
sum = 0

fN1 = 1 # Previous term
fN2 = 1 # Two terms ago
fN = fN1 + fN2  # Initialize 3rd term

while fN < limit:
    if debug:
        print(fN)
    
    if fN % 2 == 0:
        sum += fN
    
    fN2 = fN1
    fN1 = fN
    fN = fN1 + fN2

print(f'2.) {sum}')